image: docker:latest

stages:
  - build

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-node:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" app_node/.
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Compile complete and succsessfully stored to Docker Hub"